services:

  mongodb:
    image: mongo:6.0.3
    restart: always
    ports:
      - 27017:27017
    env_file: .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: $DB_USER
      MONGO_INITDB_ROOT_PASSWORD: $DB_PWD
    volumes:
      - db:/data/db
    logging:
      driver: none
  
  app:
    depends_on:
      - mongodb
    build: .
    restart: always
    ports:
      - 8888:8888
    stdin_open: true
    tty: true

volumes:
  db: